FROM nginx:latest

COPY index.html /usr/share/nginx/html/
COPY white-bread /usr/share/nginx/html/white-bread
COPY wheat-bread /usr/share/nginx/html/wheat-bread
COPY corn-bread /usr/share/nginx/html/corn-bread
